"""Update todo table schema

Revision ID: 08d0a4e35553
Revises: 
Create Date: 2024-03-15 22:41:05.572376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d0a4e35553'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('title', sa.String(), nullable=True, server_default='Default Title'))
    op.add_column('todo', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('todo', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('todo', sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='taskstatus'), nullable=True))
    op.add_column('todo', sa.Column('description', sa.String(), nullable=True))
    op.add_column('todo', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('todo', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_todo_content', table_name='todo')
    op.create_index(op.f('ix_todo_title'), 'todo', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_title'), table_name='todo')
    op.create_index('ix_todo_content', 'todo', ['content'], unique=False)
    op.drop_column('todo', 'updated_at')
    op.drop_column('todo', 'created_at')
    op.drop_column('todo', 'description')
    op.drop_column('todo', 'status')
    op.drop_column('todo', 'priority')
    op.drop_column('todo', 'deadline')
    op.drop_column('todo', 'title')
    # ### end Alembic commands ###
